name: BetterSurvival
version: '1.0'
main: thechaoticjan.betterSurvival.Main
api-version: '1.21'
commands:
  backpack:
    aliases:
      - bp
      - rucksack
  invsee:
    aliases:
      - inventar

  ping:

  rename:
    aliases:
      - umbenennen

  config:
    aliases:
      - farbe

  ec:
    aliases:
      - enderchest
      - endertruhe

  showitem:
    aliases:
      - itemzeigen
      - show

  rank:

  afk:

  testsb:
